version: '2.3'

services:

  redirect:
    image: ghcr.io/leviscop/simple-proxy:main
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectscheme.scheme=https
      - traefik.http.routers.redirect-secure.entrypoints=websecure
      - traefik.http.routers.redirect-secure.rule=Host(`map.mc.gfelite.net`)
      - traefik.http.routers.redirect-secure.service=redirect
      - traefik.http.routers.redirect-secure.tls=true
      - traefik.http.routers.redirect-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.redirect.entrypoints=web
      - traefik.http.routers.redirect.middlewares=redirect-https
      - traefik.http.routers.redirect.rule=Host(`map.mc.gfelite.net`)
      - traefik.http.services.redirect.loadbalancer.server.port=80
    environment:
      - FORWARD_HOST=mc.gfelite.net
      - FORWARD_PORT=1080
      - FORWARD_PROT=http
      - DNS=1.1.1.1
    networks:
      - gateway
